import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { ChatProvider } from "@/providers/ChatProvider";
import { UserProvider } from "@/providers/UserProvider";
import { getCurrentUser } from "@/actions/user";
import { getUserChats } from "@/actions/chat";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedInUser = await getCurrentUser();
  const initialChats = await getUserChats();

  return (
    <ClerkProvider>
      <ChatProvider initialChats={initialChats}>
        <UserProvider initialUser={loggedInUser}>
          <html lang="en">
            <body className={inter.className}>
              <Header />
              {children}
            </body>
          </html>
        </UserProvider>
      </ChatProvider>
    </ClerkProvider>
  );
}
